### PR TITLE
[Agents Extension] Default files list to "/"

### PR DESCRIPTION
**Pull request by trangevi**
Provides default to aid in user experience.

### CODE REVIEW

File: cli/azd/extensions/azure.ai.agents/internal/cmd/files.go [hunk 1]
```diff
@@ -394,7 +394,7 @@ Agent details are automatically resolved from the azd environment.`,
 				return err
 			}
 
-			remotePath := ""
+			remotePath := "/"
```
[the remark this answers is not in the document]
Comment (trangevi) [reply cli/azd/extensions/azure.ai.agents/internal/cmd/files.go:397]: Unfortunately at the moment the service doesn't seem to actually have a default root

File: cli/azd/extensions/azure.ai.agents/internal/cmd/files_test.go [hunk 2]
```diff
@@ -100,6 +100,14 @@ func TestFilesListCommand_OptionalRemotePath(t *testing.T) {
 	assert.NotNil(t, cmd.Args)
 }
 
+func TestFilesListCommand_DefaultPathIsRoot(t *testing.T) {
+	cmd := newFilesListCommand()
+
+	// The Use line should show [remote-path] as optional with "/" as default behavior.
```
Comment (jongio) [inline cli/azd/extensions/azure.ai.agents/internal/cmd/files_test.go]: This test checks static help text, not the runtime behavior. It passes regardless of what `remotePath` gets set to in the `RunE` closure.

A more useful test would invoke the command (with a stubbed client) and verify that `ListSessionFiles` receives `"/"` when no args are given - that way a regression from `"/"` back to `""` would actually fail.

**Review by jongio — COMMENTED** [review]
The code change is correct - sending `/` explicitly makes sense if the service doesn't default to root when the path parameter is omitted. The author confirmed this in the thread.

One gap: the new test only asserts help text strings (`cmd.Use` and `cmd.Long`), which would pass identically whether the default is `""` or `"/"`. It doesn't exercise the changed behavior. Consider a test that invokes the command's `RunE` (or at least inspects the constructed `FilesListAction`) to verify `remotePath` is `"/"` when no arg is provided.

**Review by JeffreyCA — APPROVED** [review]

File: cli/azd/extensions/azure.ai.agents/internal/cmd/files.go (hunk 1 above)
[the remark this answers is not in the document]
Comment (trangevi) [reply cli/azd/extensions/azure.ai.agents/internal/cmd/files.go:397]: Recent messaging is that the service may be adding a default, leaving this open until I get more details

**Review by wbreza — APPROVED** [review]
## ✅ Approved (Re-Review)

Original P0 concern (API behavior change from `"``` to `"/"``) is resolved — author confirmed the backend service requires an explicit `"/"` and has no default root.

Test coverage is meaningfully improved with the new commit:
- Table-driven unit test covers default and explicit path cases
- Integration test with `httptest.NewTLSServer` validates the query parameter is sent correctly
- Clean `client_test_helpers.go` utility follows good patterns (copyright header, adapter pattern, proper pipeline construction)

**Remaining CI items (non-blocking for approval — CI-gated):**
- `golangci-lint` failure needs resolution before merge
- PR governance check (missing linked issue)

**Review by hemarina — APPROVED** [review]

**Review by jongio — APPROVED** [review]
Incremental review: the new commit fully addresses my earlier test coverage feedback. The table-driven unit test plus the integration test with httptest give solid confidence that ListSessionFiles receives ?path=/ when no explicit path argument is provided. Clean test helper pattern for cross-package testing too. Looks good.

**Review by wbreza — APPROVED** [review]
Re-approved. No new changes since last review. The core change (defaulting remotePath to / instead of empty string) is correct, tests are solid (table-driven unit test + httptest integration test), and the test helper pattern is clean. Remaining CI items (golangci-lint, PR governance) are non-blocking for approval.

**Review by wbreza — APPROVED** [review]
## ✅ Re-Approved (No new changes)

Head commit `77d6b47` is unchanged since the prior approval on 2026-05-13. Re-posting per review policy.

The core change (defaulting `remotePath` to `"/"` instead of empty string) remains correct. Test coverage is solid:
- Table-driven unit test for default and explicit path cases
- `httptest`-based integration test validating the `?path=/` query parameter
- Clean `client_test_helpers.go` adapter pattern

**Remaining CI items (non-blocking for approval — CI-gated):**
- `golangci-lint` failure needs resolution before merge
- PR governance check (missing linked issue)

**Review by jongio — APPROVED** [review]
No issues. The one-line default change is correct (service requires explicit / per author confirmation), and the second commit adds proper test coverage: table-driven unit test for path resolution plus an httptest integration test verifying the query parameter reaches the wire.

**Review by jongio — APPROVED** [review]

File: cli/azd/extensions/azure.ai.agents/internal/cmd/files_test.go [hunk 3]
```diff
@@ -100,6 +103,55 @@ func TestFilesListCommand_OptionalRemotePath(t *testing.T) {
...
+		capturedPath = r.URL.Query().Get("path")
+		w.Header().Set("Content-Type", "application/json")
+		resp := agent_api.SessionFileList{Path: "/", Entries: []agent_api.SessionFileInfo{}}
+		_ = json.NewEncoder(w).Encode(resp)
+	}))
+	defer srv.Close()
+
+	client := agent_api.NewAgentClientForTest(srv.URL, srv.Client())
+
+	_, err := client.ListSessionFiles(t.Context(), "test-agent", "test-session", "/", DefaultAgentAPIVersion)
```
Comment (jongio) [inline cli/azd/extensions/azure.ai.agents/internal/cmd/files_test.go:150]: Two things here:

1. This won't compile once the branch is updated to current main. `ListSessionFiles` now takes a trailing `*agent_api.SessionRequestOptions` argument, so after merging main `go vet` fails on this line with `not enough arguments in call to client.ListSessionFiles`. Add the options arg when you rebase.

2. This passes `/` explicitly, so it covers the client's query-param plumbing, not the new no-arg default in the command's `RunE`. If files.go went back to `remotePath := ""`, this test would still pass. To guard the actual change, run the command with no args and assert the path that reaches the server is `/`.

File: cli/azd/extensions/azure.ai.agents/internal/cmd/files_test.go [hunk 4]
```diff
@@ -100,6 +103,55 @@ func TestFilesListCommand_OptionalRemotePath(t *testing.T) {
...
+		wantPath string
+	}{
+		{"no args defaults to root", []string{}, "/"},
+		{"explicit path is preserved", []string{"/data"}, "/data"},
+	}
+
+	for _, tt := range tests {
+		t.Run(tt.name, func(t *testing.T) {
+			// Replicate the exact logic from newFilesListCommand's RunE:
+			remotePath := "/"
```
Comment (jongio) [inline cli/azd/extensions/azure.ai.agents/internal/cmd/files_test.go:126]: This copies the `RunE` default logic instead of calling it, so it can't catch a regression in the real code. Revert files.go to `remotePath := ""` and this test stays green. Worth exercising the command's arg handling directly, or pulling the default into a small helper that both `RunE` and the test call.

File: cli/azd/extensions/azure.ai.agents/internal/pkg/agents/agent_api/client_test_helpers.go [hunk 5]
```diff
@@ -0,0 +1,41 @@
...
+	"net/http"
+
+	"github.com/Azure/azure-sdk-for-go/sdk/azcore/policy"
+	"github.com/Azure/azure-sdk-for-go/sdk/azcore/runtime"
+)
+
+// NewAgentClientForTest creates an AgentClient suitable for unit tests that use
+// httptest.NewTLSServer. It uses the provided http.Client (which trusts the test
+// server's self-signed certificate) and skips bearer token authentication.
+func NewAgentClientForTest(endpoint string, httpClient *http.Client) *AgentClient {
```
Comment (jongio) [inline cli/azd/extensions/azure.ai.agents/internal/pkg/agents/agent_api/client_test_helpers.go:16]: `client_test_helpers.go` has no `_test.go` suffix, so `NewAgentClientForTest` (which skips bearer auth) compiles into the shipped `agent_api` package as exported API. To keep it out of the production binary while still sharing it with the `cmd` tests, a small `agent_apitest` support package (imported only from tests, like `net/http/httptest`) is the usual pattern.

**Review by jongio — COMMENTED** [review]
Since this last went green, main moved and the new test no longer builds against it. On current main `ListSessionFiles` takes a trailing `*agent_api.SessionRequestOptions` argument, so after updating this branch to merge, `go vet ./internal/cmd/...` fails with `not enough arguments in call to client.ListSessionFiles`. The one-line default change in files.go is fine on its own (go vet passes on this branch in isolation); it's the added integration test that needs the extra arg once you rebase. A couple of test-coverage notes inline too.

File: cli/azd/extensions/azure.ai.agents/internal/pkg/agents/agent_api/client_test_helpers.go [hunk 6]
```diff
@@ -0,0 +1,41 @@
...
+	}
+}
+
+// httpClientTransport adapts an *http.Client to the policy.Transporter interface.
+type httpClientTransport struct {
+	client *http.Client
+}
+
+func (t *httpClientTransport) Do(req *http.Request) (*http.Response, error) {
+	return t.client.Do(req)
```
Comment (jongio) [inline cli/azd/extensions/azure.ai.agents/internal/pkg/agents/agent_api/client_test_helpers.go:40]: This line is what fails the required `lint / golangci-lint` check: gosec reports G704 (SSRF via taint analysis) because a caller-supplied `req` flows into `http.Client.Do`, and the extension's `.golangci.yaml` runs gosec over test files too, so it blocks the merge.

You don't need this adapter. `*http.Client` already satisfies `azcore/policy.Transporter` (its `Do(*http.Request) (*http.Response, error)` matches), so you can delete `httpClientTransport` and set `Transport: httpClient` directly in the `ClientOptions`. That drops the flagged line and the extra type. A `//nolint:gosec // G704: test-only transport` on this line would also clear it, but passing the client straight through is simpler.

**Review by jongio — COMMENTED** [review]
The required golangci-lint check is red from a gosec G704 finding in the new `client_test_helpers.go` (flagged inline). That's the current merge blocker.

Two items from my earlier pass are still open too:
- The integration test calls `ListSessionFiles` with the old 5-arg shape. On current main it takes a trailing `*SessionRequestOptions`, so the test won't build once this branch merges up (`not enough arguments in call to client.ListSessionFiles`).
- `TestFilesListCommand_DefaultPathIsRoot` re-implements the default-path logic instead of invoking the command, so a regression from the `/` default back to an empty string wouldn't fail it.

The one-line `files.go` change itself is fine; it's the added test scaffolding that needs another pass.

**Review by jongio — COMMENTED** [review]
Went back through this against current main. The branch hasn't moved, so the items from my last pass are all still open, but I've now got concrete results for each instead of predictions.

The `lint / golangci-lint` failure is the merge blocker: gosec G704 on `client_test_helpers.go:40` (`return t.client.Do(req)`). I verified the fix locally. Delete `httpClientTransport` and set `Transport: httpClient` directly in the `ClientOptions`, since `*http.Client` already satisfies `policy.Transporter`. That takes the package to 0 lint issues.

Merging current main into this branch still breaks the build. `files_test.go:151` calls `ListSessionFiles` with 5 args, and it now takes a trailing `*agent_api.SessionRequestOptions`:

```
vet: internal/cmd/files_test.go:151: not enough arguments in call to client.ListSessionFiles
	have (context.Context, string, string, string, string)
	want (context.Context, string, string, string, string, *agent_api.SessionRequestOptions)
```

Passing `nil` there is enough. With both of those applied, the package builds, lints clean, and `go test ./internal/cmd/...` passes.

On test coverage, I reverted `files.go` back to `remotePath := ""` (the exact bug this PR fixes) and reran the two new tests. Both still pass. So neither one guards the change, including the httptest integration test, which passes `/` explicitly rather than going through the command's no-arg path. Pulling the default into a small helper that both `RunE` and the test call would close that.

The one-line `files.go` change itself merges clean and isn't the problem here. It's the added test scaffolding that needs another pass.

<sub>🤖 agent jongio</sub>

**Review by jongio — COMMENTED** [review]
Re-checked this against today's main (7d34c7eb9). Both blockers from my last pass still reproduce, so nothing's moved: gosec G704 on `client_test_helpers.go:40` keeps `lint / golangci-lint` red, and `files_test.go:151` still fails `go vet` after merging main with `not enough arguments in call to client.ListSessionFiles`. Fixes are in my earlier comments, no need to repeat them here.

One blocker I haven't flagged before: `PR Governance` is failing on its "Check linked issue" step, and it's been red on every run since May 5. The PR has no linked issue and the description is a single sentence. Adding `Fixes #NNNN` to the body clears that one.

I also left a note on the files.go thread about the service-side default question that's been open since May, since it decides whether this change is still needed.

File: cli/azd/extensions/azure.ai.agents/internal/cmd/files.go (hunk 1 above)
[the remark this answers is not in the document]
Comment (jongio) [reply cli/azd/extensions/azure.ai.agents/internal/cmd/files.go:397]: This has been sitting open since May 5. If the service did end up adding a default root, sending `path=/` explicitly stops being a fix and just becomes a redundant query param, so it's worth settling before this merges.

Did the service-side default ever land? If it did, the one-line change here probably isn't needed anymore. If it didn't, that's worth capturing in the PR description so the next person doesn't have to re-derive why the explicit `/` is required.
